name: Sync to Private Repo on PR Merge

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  sync:
    # Only run if the PR was actually merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to private repository
        run: |
          # Add private repo as remote with authentication
          # Note: PRIVATE_SYNC_TOKEN must have write access to the private repo
          git remote add private https://x-access-token:${{ secrets.PRIVATE_SYNC_TOKEN }}@github.com/anthropics/claude-cookbooks-private.git
          git fetch private

          # Try to push (fast-forward only)
          if git push private main; then
            echo "✅ Successfully pushed to private repository"
          else
            echo "❌ Failed to push to private repository"
            echo "This likely means the private repo has diverged from public."
            echo "Manual intervention required to resolve."
            exit 1
          fi

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Sync to Private Failed - Manual Resolution Needed',
              body: `## Sync Failure Details

              **Workflow Run:** ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}
              **PR:** #${context.payload.pull_request.number} - ${context.payload.pull_request.title}
              **Merged by:** @${context.payload.pull_request.merged_by.login}

              The automatic sync from public to private repository failed. This typically happens when:

              1. The private repository has commits that aren't in the public repository
              2. There was a network or API issue

              ## Resolution Steps

              \`\`\`bash
              # Manually sync the repositories
              git fetch public  # public repo
              git fetch origin  # private repo
              git checkout main

              # Check the divergence
              git log public/main..origin/main  # commits in private but not public
              git log origin/main..public/main  # commits in public but not private

              # Merge and resolve conflicts:
              git merge public/main
              # Resolve conflicts if any
              git push origin main  # push to private
              git push public main  # push to public
              \`\`\`

              After resolving, close this issue.`,
              labels: ['sync-failure', 'urgent']
            })
